'use strict';
const C=RailCore,D=RAIL_DATA,LEGACY_KEY='hiragana-railway-v2',ACTIVE_PROFILE_KEY='mojitetsu_active_profile',PROFILES={sakkun:{name:'さっくん',courses:['hiragana','katakana','kanji']},kanachan:{name:'かなちゃん',courses:['hiragana']}},APP_VERSION=document.querySelector('meta[name="app-version"]')?.content||'不明',COUNTS=Object.fromEntries(Object.entries(D.characters).map(([c,v])=>[c,v.paths.length]));
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',screens=['home','game','reward','album','parent'];
// Home platforms. A course appears only once data/courses.js defines it, numbered in this order.
const LINES={hiragana:{name:'ひらがな',color:'#c8630f'},katakana:{name:'カタカナ',color:'#1f6fa8'},kanji:{name:'かんじ',color:'#6b3fa0'}};
const linesFor=id=>Object.keys(LINES).filter(course=>C.GROUPS[course]&&PROFILES[id].courses.includes(course));
const ownedCount=st=>st.cards.filter(id=>D.cards.some(c=>c.id===id)).length;
const keyFor=id=>'mojitetsu_'+id+'_state_v2';
const SPEECH_SUPPORTED=typeof window.speechSynthesis?.speak==='function'&&typeof window.SpeechSynthesisUtterance==='function';
let profileId='sakkun',KEY=keyFor(profileId),state=C.fresh(),lastStored=null,canSave=true,blocked=false,currentScreen='home',pointer=null,paths=[],samples=[],hintOn=false,animation=0,animationToken=0,demoing=false,currentUtterance=null,speechToken=0,pendingImport=null,pendingImportProfile=null,pendingImportStatus='import-status';
let recallPhase='off',recallTimer=0,recallRemaining=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function warn(text){$('storage-warning').hidden=false;$('storage-warning').textContent=text;}
function conflict(){blocked=true;cancelRecall();cancelDemo();clearTrail();if(!$('conflict').open)$('conflict').showModal();}
function persist(){if(blocked)return false;if(!canSave)return false;try{const current=localStorage.getItem(KEY);if(current!==lastStored){conflict();return false;}state.revision++;const data=JSON.stringify(state);localStorage.setItem(KEY,data);lastStored=data;return true;}catch{canSave=false;warn('このブラウザには保存できません。遊ぶことはできますが、閉じる前に「おうちの方へ」から記録を書き出してください。');return false;}}
function profile(){return PROFILES[profileId];}
function showLoadError(){canSave=false;blocked=true;warn(profile().name+'の保存された記録を読み込めません。元のデータは残しています。');const b=document.createElement('button');b.textContent='保存せず一時的に遊ぶ';b.onclick=()=>{blocked=false;b.remove();warn('一時的なプレイです。元の記録は上書きしません。復元は「おうちの方へ」から行えます。');};$('storage-warning').append(b);}
function loadProfile(id,{remember=true}={}){profileId=id;KEY=keyFor(id);state=C.fresh();lastStored=null;canSave=true;blocked=false;$('storage-warning').hidden=true;$('storage-warning').replaceChildren();try{if(remember)localStorage.setItem(ACTIVE_PROFILE_KEY,id);let stored=localStorage.getItem(KEY);if(!stored&&id==='sakkun'){const legacy=localStorage.getItem(LEGACY_KEY);if(legacy){state=C.validate(JSON.parse(legacy),COUNTS);stored=JSON.stringify(state);localStorage.setItem(KEY,stored);}}lastStored=stored;if(stored)state=C.validate(JSON.parse(stored),COUNTS);}catch{showLoadError();}renderProfile();}
try{const selected=localStorage.getItem(ACTIVE_PROFILE_KEY);if(PROFILES[selected])profileId=selected;}catch{}
loadProfile(profileId,{remember:false});
window.addEventListener('storage',e=>{if((e.key===KEY||e.key===null)&&e.newValue!==lastStored)conflict();});$('reload').onclick=()=>location.reload();
const session=()=>C.active(state),q=()=>session()?.questions[session().index];
function renderProfile(){const p=profile();document.body.dataset.profile=profileId;for(const button of document.querySelectorAll('button[data-profile]')){const selected=button.dataset.profile===profileId;button.setAttribute('aria-pressed',String(selected));button.classList.toggle('selected',selected);}$('current-profile').textContent=p.name;$('game-profile').textContent=p.name;$('parent-profile').textContent=p.name;$('backup-profile').textContent=p.name;$('album-title').textContent=p.name+'の ずかん';}
function selectProfile(id){if(!PROFILES[id]||id===profileId)return;pause('ユーザー切り替え');loadProfile(id);home();}
function svgEl(tag,attrs){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
function cancelDemo(){animationToken++;cancelAnimationFrame(animation);demoing=false;$('demo-dot').hidden=true;$('demo').disabled=false;}
function stopSpeech(){speechToken++;if(SPEECH_SUPPORTED)window.speechSynthesis.cancel();currentUtterance=null;$('speak').classList.remove('speaking');}
function clearTrail(){pointer=null;$('trail').setAttribute('d','');}
function pause(reason){if(currentScreen==='game'&&pointer&&q()){C.uncertain(q(),reason);persist();}clearTrail();cancelDemo();stopSpeech();cancelRecall();}
function screen(id){pause('画面移動');currentScreen=id;document.body.classList.toggle('home-screen',id==='home');for(const x of screens)$(x).hidden=x!==id;document.body.classList.toggle('child-screen',id!=='parent');document.body.classList.toggle('playing',id==='game');document.documentElement.classList.toggle('playing',id==='game');$('back').hidden=id==='home'||id==='game';if(id!=='game')window.scrollTo(0,0);}
function storedOwned(id){if(id===profileId)return ownedCount(state);try{const x=JSON.parse(localStorage.getItem(keyFor(id)));return Array.isArray(x?.cards)?ownedCount(x):0;}catch{return 0;}}
function home(){screen('home');const s=session(),interrupted=!!(s&&!s.reward),course=interrupted?courseOf(s):null,canChooseResume=profileId==='sakkun'&&interrupted,owned=ownedCount(state),total=D.cards.length;
 $('resume-area').hidden=!canChooseResume;$('lines-area').hidden=canChooseResume;$('resume-detail').textContent=canChooseResume?(LINES[course]?.name||'')+' '+(s.index+1)+'/5もん のつづき':'';
 $('lines').replaceChildren(...linesFor(profileId).map((c,i)=>{const b=document.createElement('button'),no=String(i+1),resume=interrupted&&course===c;b.type='button';b.className='line-button';b.dataset.course=c;b.style.setProperty('--line-color',LINES[c].color);b.innerHTML='<span class="line-number"></span><span class="line-text"><small></small><b></b><small class="line-sub"></small></span>';b.querySelector('.line-number').textContent=no;b.querySelector('.line-text small').textContent=no+'ばんせん';b.querySelector('b').textContent=LINES[c].name;b.querySelector('.line-sub').textContent=resume?'つづき '+(s.index+1)+'/5もん':C.GROUPS[c].length+'もじ';b.onclick=()=>begin(c);return b;}));
 $('departure-dest').textContent=owned<total?(owned+1)+'まいめの カード':state.shinyCards.length<total?'キラカード':'きょうの カード';$('departure-left').textContent='あと '+(interrupted?5-s.index:5)+'もじ';
 $('station-number').textContent=String(owned).padStart(2,'0');$('owned').textContent=owned+' / '+total;
 const recent=state.cards.filter(id=>D.cards.some(c=>c.id===id)).slice(-3).map(id=>D.cards.find(c=>c.id===id)),latest=recent.at(-1),heroSrc=latest?.image||'assets/500.jpg';if($('hero-photo').getAttribute('src')!==heroSrc)$('hero-photo').src=heroSrc;$('hero-photo').alt=latest?.name||'';$('hero-tag').textContent=latest?'さいきん あえた でんしゃ':'もじてつえきへ ようこそ';$('hero-name').textContent=latest?.reading||'';$('hero-name').hidden=!latest;$('collection-thumbs').replaceChildren(...(recent.length?recent:[null]).map(card=>{if(!card)return Object.assign(document.createElement('span'),{className:'thumb-empty',textContent:'？'});const img=document.createElement('img');img.src=card.image;img.alt='';return img;}));
 for(const el of document.querySelectorAll('[data-owned-for]'))el.textContent='ずかん '+storedOwned(el.dataset.ownedFor)+' / '+total+'まい';}
const courseOf=s=>s?.course||Object.keys(C.GROUPS).find(course=>s?.questions.some(item=>C.GROUPS[course].includes(item.char))&&course!=='hiragana')||'hiragana';
function begin(course='hiragana'){if(blocked)return;if(!session()||session().reward){C.start(state,course);persist();}if(blocked)return;screen('game');loadQuestion();}
function loadQuestion(){cancelRecall();cancelDemo();clearTrail();stopSpeech();const s=session(),item=q();if(!item){showReward();return;}const character=D.characters[item.char];hintOn=!!s.guide||item.assisted;if(!item.startedAt)item.startedAt=new Date().toISOString();if(s.guide&&!isRecall()&&!item.complete)C.assist(item,'補助モード');persist();$('strokes').replaceChildren();paths=character.paths.map(d=>{const p=svgEl('path',{d,class:'stroke ghost'});$('strokes').append(p);return p;});samples=paths.map(p=>{const len=p.getTotalLength(),n=Math.ceil(len);return Array.from({length:n+1},(_,i)=>{const pt=p.getPointAtLength(i*len/n);return{x:pt.x,y:pt.y};});});$('board').setAttribute('aria-label',item.char+(character.reading?'（'+character.reading+'）':'')+'を指で書くところ');const label=$('char-label');label.textContent='「'+item.char+'」';if(character.reading){const reading=document.createElement('small');reading.className='char-reading';reading.textContent=character.reading;label.append(reading);}const speak=$('speak');speak.hidden=!SPEECH_SUPPORTED;if(SPEECH_SUPPORTED)speak.setAttribute('aria-label','「'+item.char+(character.reading?'、'+character.reading:'')+'」の おとをきく');$('round-label').textContent=(s.index+1)+' / 5';$('stations').innerHTML=s.questions.map((_,i)=>'<span class="'+(i<s.index?'done':i===s.index?'current':'')+'"></span>').join('');render();message(item.complete?'できた！ つぎへ すすもう':'じぶんで かいてみよう');if(isRecall())startRecall();}
function speakCurrentChar(){const item=q();if(!SPEECH_SUPPORTED||currentScreen!=='game'||!item)return;const character=D.characters[item.char];stopSpeech();const token=speechToken,utterance=new SpeechSynthesisUtterance(character.speech||character.reading||item.char);currentUtterance=utterance;utterance.lang='ja-JP';utterance.rate=.85;utterance.pitch=1;utterance.volume=1;const localJapanese=(window.speechSynthesis.getVoices?.()||[]).find(voice=>voice.localService&&/^ja(?:-|$)/i.test(voice.lang));if(localJapanese)utterance.voice=localJapanese;const finish=()=>{if(currentUtterance!==utterance||speechToken!==token)return;currentUtterance=null;$('speak').classList.remove('speaking');};utterance.onstart=()=>{if(currentUtterance===utterance&&speechToken===token)$('speak').classList.add('speaking');};utterance.onend=finish;utterance.onerror=finish;$('speak').classList.add('speaking');try{window.speechSynthesis.speak(utterance);}catch{finish();}}
$('speak').addEventListener('click',speakCurrentChar);
function message(t){$('message').textContent=t;}
function render(){const item=q();if(!item)return;paths.forEach((p,i)=>p.setAttribute('class','stroke '+(i<item.stroke?'finished':'ghost')));$('hint-mark').replaceChildren();$('stroke-label').textContent=item.complete?'できた！':(item.stroke+1)+'かくめ';$('next').hidden=!item.complete;$('hint').disabled=item.complete;$('demo').disabled=item.complete||demoing;$('next').textContent=session().index===4?'カードを もらう →':'つぎへ →';if((hintOn||isRecall())&&!item.complete&&(!isRecall()||['writing','hint'].includes(recallPhase))){const p=samples[item.stroke][0];$('hint-mark').append(svgEl('circle',{cx:p.x,cy:p.y,r:4.5,fill:'#fffefa',stroke:'#b78736','stroke-width':1}));const text=svgEl('text',{x:p.x,y:p.y+1.5,'text-anchor':'middle','font-size':4.5,fill:'#7b5416'});text.textContent=item.stroke+1;$('hint-mark').append(text);}renderRecall();}
function help(reason='ヒント',text='まるから しゅっぱつ！'){const item=q();if(!item||item.complete)return;C.assist(item,reason);hintOn=true;persist();render();message(text);}
function pos(e){return new DOMPoint(e.clientX,e.clientY).matrixTransform($('board').getScreenCTM().inverse());}
function drawTrail(c){const p=paths[q().stroke],len=p.getTotalLength();$('trail').setAttribute('d',p.getAttribute('d'));$('trail').style.strokeDasharray=len;$('trail').style.strokeDashoffset=len*(1-c.progress/(c.points.length-1));}
$('board').addEventListener('pointerdown',e=>{if(blocked||currentScreen!=='game'||q().complete||demoing||pointer||document.hidden||(isRecall()&&!['writing','hint'].includes(recallPhase))||e.button>0)return;e.preventDefault();const p=pos(e);pointer={id:e.pointerId,last:p,travel:0,candidates:C.candidates(samples,p),chosen:null,locked:null,points:[{x:p.x,y:p.y}]};$('board').setPointerCapture(e.pointerId);});
function move(e){if(!pointer||pointer.id!==e.pointerId)return;e.preventDefault();const p=pos(e),pnt=pointer;if(isRecall()){if(p.x < -40||p.x >149||p.y < -40||p.y >149){endPointer(e,true);return;}pnt.travel+=C.dist(pnt.last,p);pnt.last=p;if(C.dist(pnt.points.at(-1),p)>.4){pnt.points.push({x:p.x,y:p.y});if(pnt.points.length>1024){endPointer(e,true);return;}}$('trail').style.strokeDasharray='none';$('trail').style.strokeDashoffset=0;$('trail').setAttribute('d',inkPath(pnt.points));return;}if(pnt.locked){pnt.last=p;message('ゆびを はなそう');return;}const distance=C.dist(pnt.last,p);pnt.travel+=distance;for(const cand of pnt.candidates)C.advance(cand,pnt.last,p);pnt.last=p;const chosen=pnt.chosen?.alive?pnt.chosen:C.resolve(pnt.candidates,pnt.travel),item=q(),mistake=chosen&&(chosen.index!==item.stroke||chosen.reverse)?chosen:C.wrongChoice(pnt.candidates,item.stroke,pnt.travel);if(mistake){C.recordMistake(session(),item,mistake);const kind=mistake.index!==item.stroke?'order':'direction',txt=kind==='direction'?'まるから、こっちへ かこう':item.char==='や'&&item.stroke===1?'つぎは みぎうえの みじかい せん':item.char==='せ'&&item.stroke===1?'つぎは みぎの たてせん':'つぎは この せんだよ';clearTrail();help('自動案内',txt);return;}if(chosen){pnt.chosen=chosen;if(chosen.reachedEnd)pnt.locked=chosen;drawTrail(chosen);message(chosen.reachedEnd?'ゆびを はなそう':'そのまま かこう');}
 if(pnt.travel>4&&!pnt.candidates.some(c=>c.alive)){C.uncertain(q(),'軌跡を判別できない');clearTrail();help('位置の補助','せんの ちかくから、もういちど');}}
$('board').addEventListener('pointermove',move);
function endPointer(e,cancel=false){if(!pointer||pointer.id!==e.pointerId)return;if(isRecall()){endRecall(e,cancel);return;}const p=pointer,item=q();const c=p.locked||p.chosen||C.resolve(p.candidates,p.travel);const success=!cancel&&c?.alive&&c.reachedEnd&&c.index===item.stroke&&!c.reverse&&p.travel>=4;clearTrail();if(success){C.firstRecord(item,'correct',item.stroke,'forward');item.stroke++;item.complete=item.stroke===paths.length;hintOn=!!session().guide;if(item.complete)message('できた！');else message('つぎは どこから？');persist();render();}else{C.uncertain(item,cancel?'タッチ中断':p.travel<4?'タップ・短い入力':'画の途中で指離し');persist();help('位置の補助',cancel?'もういちど この せんから':'この せんを、もういちど');}}
$('board').addEventListener('pointerup',e=>{if(pointer)move(e);endPointer(e);});$('board').addEventListener('pointercancel',e=>endPointer(e,true));$('board').addEventListener('lostpointercapture',e=>endPointer(e,true));
$('board').addEventListener('touchmove',e=>{if(currentScreen==='game'&&e.cancelable)e.preventDefault();},{passive:false});
window.addEventListener('resize',()=>{if(currentScreen==='game'){pause('画面サイズ変更');if(isRecall())startRecall();else{render();message('つづきから かこう');}}});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('バックグラウンド移行');else if(currentScreen==='game'&&isRecall()&&!blocked)startRecall();});window.addEventListener('pagehide',()=>pause('ページ離脱'));window.addEventListener('pageshow',e=>{if(e.persisted&&currentScreen==='game'&&isRecall()&&!blocked)startRecall();});
for(const type of ['dblclick','gesturestart'])document.addEventListener(type,e=>{if(document.body.classList.contains('child-screen')&&e.cancelable)e.preventDefault();},{passive:false});
$('hint').onclick=()=>{if(blocked)return;if(isRecall()){peekRecall();return;}pause('ヒント選択');help();};
$('demo').onclick=()=>{if(blocked||isRecall()||q()?.complete)return;pause('お手本選択');help('お手本');demoing=true;$('demo').disabled=true;const token=animationToken,item=q(),path=paths[item.stroke],len=path.getTotalLength(),duration=Math.max(800,len*13),start=performance.now();message('この せんを みていてね');function step(now){if(token!==animationToken)return;const f=Math.min(1,(now-start)/duration);$('trail').setAttribute('d',path.getAttribute('d'));$('trail').style.strokeDasharray=len;$('trail').style.strokeDashoffset=len*(1-f);const p=path.getPointAtLength(len*f);$('demo-dot').hidden=false;$('demo-dot').setAttribute('cx',p.x);$('demo-dot').setAttribute('cy',p.y);if(f<1)animation=requestAnimationFrame(step);else{cancelDemo();clearTrail();render();message('まるから かいてみよう');}}animation=requestAnimationFrame(step);};
$('next').onclick=()=>{if(blocked||!q()?.complete)return;const s=session();delete q().ink;s.index++;if(s.index===5){C.award(state,D.cards.map(c=>c.id));persist();showReward();}else{persist();loadQuestion();}};
function isRecall(){return session()?.writingMode==='recall';}
function inkPath(points){return points.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ');}
function cancelRecall(){clearTimeout(recallTimer);recallTimer=0;if(recallPhase!=='off'){recallPhase='suspended';$('game').dataset.recall='suspended';$('recall-countdown').hidden=true;}}
function renderRecall(){
 const item=q(),recall=isRecall();
 $('writing-modes').hidden=false;
 $('mode-trace').setAttribute('aria-pressed',String(!recall));$('mode-recall').setAttribute('aria-pressed',String(recall));
 $('mode-trace').disabled=$('mode-recall').disabled=!!item.complete;
 $('recall-grid').toggleAttribute('hidden',!recall);$('demo').hidden=recall;$('hint').textContent=recall?'💡 ヒント':'ヒント';
 $('written').replaceChildren();
 if(!recall){recallPhase='off';delete $('game').dataset.recall;$('recall-countdown').hidden=true;return;}
 $('game').dataset.recall=recallPhase;
 const character=D.characters[item.char],reading=character.reading||item.char,show=recallPhase==='preview'||item.complete;
 $('char-label').textContent=show?'「'+item.char+'」'+(character.reading?' '+reading:''):reading;
 $('board').setAttribute('aria-label',reading+'を おぼえて書くところ');
 $('speak').setAttribute('aria-label',reading+'の おとをきく');
 $('hint').disabled=item.complete||!['writing','hint'].includes(recallPhase);
 $('recall-countdown').hidden=recallPhase!=='preview';$('recall-countdown').textContent=recallRemaining;
 for(const line of item.ink||[])$('written').append(svgEl('path',{d:inkPath(line),class:'stroke'}));
}
function startRecall(){
 cancelRecall();const item=q();if(!item||!isRecall())return;
 if(item.complete){recallPhase='complete';render();message('大開通！ すごーい！ おぼえてたね！');return;}
 item.recallUsed=true;persist();if(blocked)return;
 recallPhase='preview';recallRemaining=3;render();message('3びょう よーくみて、かたちを おぼえよう！');
 function tick(){if(blocked||currentScreen!=='game'||document.hidden)return;recallRemaining--;if(recallRemaining){render();recallTimer=setTimeout(tick,1000);}else{recallPhase='writing';render();message('おもいだして かいてみよう');}}
 recallTimer=setTimeout(tick,1000);
}
function peekRecall(){
 if(!q()||q().complete||!['writing','hint'].includes(recallPhase))return;
 if(pointer){C.uncertain(q(),'ヒント選択');clearTrail();}
 clearTimeout(recallTimer);C.assist(q(),'チラ見せヒント');persist();if(blocked)return;
 recallPhase='hint';render();message('ちょっと みてみよう');
 recallTimer=setTimeout(()=>{if(blocked||!isRecall()||currentScreen!=='game')return;recallPhase='writing';render();message('おもいだして かいてみよう');},1000);
}
function endRecall(e,cancel){
 const p=pointer,item=q(),chosen=cancel?null:C.recallMatch(samples,p.points,courseOf(session())!=='kanji');clearTrail();
 if(chosen&&chosen.index===item.stroke&&!chosen.reverse){
  C.firstRecord(item,'correct',item.stroke,'forward');item.ink??=[];
  // Keep only the current question's bounded ink for interruption/backup.
  const n=Math.min(128,p.points.length);item.ink.push(Array.from({length:n},(_,i)=>{const v=p.points[Math.round(i*(p.points.length-1)/(n-1))];return{x:Math.round(v.x*100)/100,y:Math.round(v.y*100)/100};}));
  item.stroke++;item.complete=item.stroke===paths.length;
  if(item.complete){clearTimeout(recallTimer);recallPhase='complete';}
  persist();render();message(item.complete?'大開通！ すごーい！ おぼえてたね！':'いいね！ つぎの せんを かこう');
 }else{
  if(chosen)C.recordMistake(session(),item,chosen);else C.uncertain(item,cancel?'タッチ中断':'想起の判定保留');
  persist();render();message(cancel?'つづきから かこう':chosen?'まるから じゅんばんに かこう':'だいじょうぶ。ヒントも つかえるよ');
 }
}
function setWritingMode(mode){
 if(blocked||!session()||q()?.complete||session().writingMode===mode)return;
 pause('かきかた切り替え');const item=q();
 if(item.stroke>0||item.recallUsed)C.assist(item,'かきかた切り替え');
 if(mode==='recall'&&!item.ink)item.ink=samples.slice(0,item.stroke).map(line=>Array.from({length:Math.min(128,line.length)},(_,i)=>line[Math.round(i*(line.length-1)/(Math.min(128,line.length)-1))]));
 if(mode==='trace')delete item.ink;
 session().writingMode=mode;persist();loadQuestion();
}
$('mode-trace').onclick=()=>setWritingMode('trace');$('mode-recall').onclick=()=>setWritingMode('recall');
function photo(img,card){const frame=img.closest('.reward-photo-frame');img.alt=card.name;img.hidden=false;img.nextElementSibling?.classList.contains('photo-error')&&img.nextElementSibling.remove();img.onload=()=>frame?.classList.remove('loading');img.onerror=()=>{frame?.classList.remove('loading');img.hidden=true;const box=document.createElement('div');box.className='photo-error';box.textContent='しゃしんを よみこめませんでした。';const b=document.createElement('button');b.textContent='もういちど';b.onclick=()=>{frame?.classList.add('loading');photo(img,card);};box.append(b);img.after(box);};img.src=card.image;if(frame&&img.complete&&img.naturalWidth>0)frame.classList.remove('loading');}
function showReward(){const s=session(),card=D.cards.find(c=>c.id===s?.reward);if(!card){home();return;}screen('reward');const shiny=state.shinyCards.includes(card.id);$('reward-card').classList.toggle('shiny',shiny);$('reward-stars').hidden=!shiny;$('reward-photo-frame').classList.add('loading');photo($('reward-photo'),card);$('reward-title').textContent=s.shinyAwarded?'キラカードに しんか！':s.repeat?'きょうの 1まい！':'カードを ゲット！';$('reward-kicker').textContent=s.shinyAwarded?'SHINY TRAIN CARD':s.repeat?'TODAY’S TRAIN':'NEW TRAIN CARD';$('reward-name').textContent=card.reading;$('reward-category').textContent=card.category;$('reward-number').textContent=card.name;$('reward-text').textContent=s.shinyAwarded?'書き順ばっちり！ ★2に しんかしたよ。':state.cards.filter(id=>D.cards.some(c=>c.id===id)).length===D.cards.length?'ぜんぶ あつまった！ また あそぼう。':'5もじ、さいごまで できたね。';}
function album(){screen('album');const owned=state.cards.filter(id=>D.cards.some(c=>c.id===id));$('album-count').textContent=owned.length+' / '+D.cards.length;$('shiny-count').textContent='キラカード ★2 '+state.shinyCards.filter(id=>owned.includes(id)).length+' / '+D.cards.length;$('cards').replaceChildren();for(const card of D.cards){if(!owned.includes(card.id)){const empty=document.createElement('div');empty.className='empty-card';empty.innerHTML='<b>？</b><span>これから あえる でんしゃ</span>';$('cards').append(empty);continue;}const button=document.createElement('button');button.className='train-card';const shiny=state.shinyCards.includes(card.id);button.classList.toggle('shiny',shiny);const img=document.createElement('img');photo(img,card);const text=document.createElement('div');text.innerHTML='<small>'+esc(card.category)+'</small>'+esc(card.reading);button.append(img,text);if(shiny){const stars=document.createElement('span');stars.className='shiny-stars';stars.textContent='★2';button.append(stars);}button.onclick=()=>detail(card);$('cards').append(button);}}
function detail(card){const shiny=state.shinyCards.includes(card.id);$('detail').classList.toggle('shiny',shiny);$('detail-stars').hidden=!shiny;photo($('detail-photo'),card);$('detail-category').textContent=card.category;$('detail-name').textContent=card.reading;$('detail-fact').textContent=card.fact;$('detail-credit').innerHTML='<p>'+esc(card.name)+'</p><p>原題：'+esc(card.sourceTitle)+'</p><p>'+esc(card.credit)+' / <a target="_blank" rel="noopener" href="'+esc(card.source)+'">写真原典</a> / <a target="_blank" rel="noopener" href="'+esc(card.licenseUrl)+'">'+esc(card.license)+'</a></p><p>'+esc(card.change)+'</p><a target="_blank" rel="noopener" href="'+esc(card.factSource)+'">豆知識の根拠</a>（'+esc(card.checked)+'確認）';$('detail').showModal();}
const kinds={order:'順番',direction:'方向',uncertain:'判定保留',unobserved:'補助から開始',correct:'正しい画を選択'};
function parent(){screen('parent');showOfflineStatus();const rows=state.sessions.flatMap(s=>s.questions.filter(q=>q.startedAt).map(q=>({q,date:q.startedAt}))),groups=linesFor(profileId).map(course=>[course,C.GROUPS[course]]);$('record-range').textContent=rows.length?'記録 '+rows.length+'問 ／ '+new Date(state.sessions[0].createdAt).toLocaleDateString('ja-JP')+'〜（直近100回分まで）':'まだ記録はありません。';const unknownCards=state.cards.filter(id=>!D.cards.some(c=>c.id===id)).length,unknownQuestions=rows.filter(r=>!C.CHARS.includes(r.q.char)).length;if(unknownCards||unknownQuestions)$('record-range').textContent+=' ／ この版では未対応のカード '+unknownCards+'件・文字記録 '+unknownQuestions+'件は保持しています。';$('records').replaceChildren();
 for(const [course,chars]of groups){const heading=document.createElement('h2');heading.className='record-group';heading.textContent=LINES[course].name;$('records').append(heading);for(const char of chars){const entries=rows.filter(r=>r.q.char===char),total=entries.length;const independent=entries.filter(({q})=>q.complete&&!q.assisted&&!q.uncertain&&Object.values(q.records).every(r=>r.kind==='correct'&&!r.assisted)).length;const helped=entries.filter(({q})=>q.complete&&q.assisted).length;const mistakes=entries.filter(({q})=>Object.values(q.records).some(r=>r.kind==='order'&&!r.assisted)).length;const directions=entries.filter(({q})=>Object.values(q.records).some(r=>r.kind==='direction'&&!r.assisted)).length;const uncertain=entries.filter(({q})=>q.uncertain).length;const record=document.createElement('details');record.className='record';const sum=document.createElement('summary');sum.innerHTML='<span class="letter">'+char+'</span><span class="count">'+(total?'出題 '+total+'回 · 案内なし完了 '+independent+'回<br>順番の取り違え '+mistakes+'回 · 方向の取り違え '+directions+'回 · 補助付き完了 '+helped+'回 · 保留/中断 '+uncertain+'回':'未出題')+'</span>';record.append(sum);const list=document.createElement('ul');for(const {q,date}of entries.slice(-10).reverse()){const li=document.createElement('li');let t=new Date(date).toLocaleString('ja-JP')+'：'+(q.recallUsed?'おぼえて書く（切替を含む）・':'なぞり書き・')+(q.complete?'完了':'未完了')+(q.assisted?'（補助あり）':'');for(const r of Object.values(q.records)){t+=' ／ '+(r.expected+1)+'画目：'+kinds[r.kind]+(r.observed!==null?' → '+(r.observed+1)+'画目を選択':'')+(r.direction==='reverse'?'・逆方向':'')+(r.assisted?'［補助後］':'')+(r.help?'［'+r.help+'］':'')+(r.interrupted?'［'+r.interrupted+'］':'');}li.textContent=t;list.append(li);}record.append(list);const b=document.createElement('button');b.textContent=state.settings.focus.includes(char)?'重点に設定済み':'次にも確かめる';b.onclick=()=>{if(!state.settings.focus.includes(char))state.settings.focus.push(char);persist();parent();};record.append(b);$('records').append(record);}}
 for(const [id,key]of [['focus-options','focus'],['pool-options','pool']]){$(id).replaceChildren();for(const [course,chars]of groups){const group=document.createElement('div');group.className='option-group';const title=document.createElement('strong');title.textContent=LINES[course].name;group.append(title);for(const c of chars){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=state.settings[key].includes(c);input.onchange=()=>{state.settings[key]=input.checked?[...state.settings[key],c]:state.settings[key].filter(x=>x!==c);persist();$('settings-result').textContent='次の5問から反映します。';};label.append(input,document.createTextNode(' '+c));group.append(label);}$(id).append(group);}}$('guide').checked=state.settings.guide;}
$('guide').onchange=()=>{state.settings.guide=$('guide').checked;persist();};
$('app-version').textContent=APP_VERSION;
// Offline: only available on https or localhost. Photos are counted from this version's cache.
const OFFLINE_CACHE='mojitetsu-'+APP_VERSION,offlineSupported='serviceWorker' in navigator&&'caches' in window;
if(offlineSupported)navigator.serviceWorker.register('sw.js?v='+encodeURIComponent(APP_VERSION)).catch(()=>{});
async function showOfflineStatus(){const el=$('offline-status');if(!offlineSupported){el.textContent='オフライン：この開き方では使えません（公開URLで開くと使えます）。';return;}try{const total=D.cards.length;if(!await caches.has(OFFLINE_CACHE)){el.textContent='オフライン：準備中です。通信できる場所でしばらく開いておいてください。';return;}const cache=await caches.open(OFFLINE_CACHE),ready=!!await cache.match('index.html');let photos=0;for(const card of D.cards)if(await cache.match(card.image))photos++;el.textContent=ready&&photos===total?'オフライン：準備できています（写真 '+photos+' / '+total+'まい）。通信がなくても遊べます。':'オフライン：準備中です（写真 '+photos+' / '+total+'まい）。通信できる場所でしばらく開いておいてください。';}catch{el.textContent='オフライン：状態を確認できませんでした。';}}
$('record-range').after($('update-app').closest('details'),$('copy-backup').closest('details'));
$('update-app').onclick=async()=>{const button=$('update-app');button.disabled=true;$('update-status').textContent='最新版を確認しています…';try{const url=new URL('index.html',document.baseURI);url.searchParams.set('update',Date.now().toString());const response=await fetch(url.href,{cache:'no-store'});if(!response.ok)throw Error('通信エラー '+response.status);const html=await response.text();if(!/<meta name="app-version" content="[^"]+">/.test(html))throw Error('更新データを確認できませんでした');$('update-status').textContent='最新版を開きます。記録はそのまま残ります。';location.replace(url.href);}catch(error){button.disabled=false;$('update-status').textContent='更新できませんでした：'+error.message+'。通信を確認して、もう一度お試しください。';}};
const backupData=()=>({backupVersion:1,profile:profileId,profileName:profile().name,exportedAt:new Date().toISOString(),state});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(backupData(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mojitetsu-'+profileId+'-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function stageImport(text,status){try{if(!text.trim())throw Error('バックアップ文字列が空です');if(text.length>3000000)throw Error('データが大きすぎます');const parsed=JSON.parse(text),wrapped=parsed?.backupVersion===1&&parsed.state;pendingImport=C.validate(wrapped?parsed.state:parsed,COUNTS);pendingImportProfile=wrapped&&PROFILES[parsed.profile]?parsed.profile:null;pendingImportStatus=status;$('restore-summary').textContent='カード '+pendingImport.cards.length+'種類・キラ '+pendingImport.shinyCards.length+'枚・'+pendingImport.sessions.length+'回分の記録です。';$('restore-target').textContent=(pendingImportProfile?PROFILES[pendingImportProfile].name+'のバックアップを、':'旧形式のバックアップを、')+'現在選択中の '+profile().name+' へ復元します。';$(status).textContent='';$('restore').showModal();return true;}catch(error){pendingImport=null;pendingImportProfile=null;$(status).textContent='読み込めません：'+error.message;return false;}}
$('copy-backup').onclick=async()=>{const text=JSON.stringify(backupData(),null,2),area=$('backup-text');area.value=text;let copied=false;try{await navigator.clipboard.writeText(text);copied=true;}catch{area.focus();area.select();try{copied=document.execCommand('copy');}catch{copied=false;}}$('backup-status').textContent=copied?profile().name+'のバックアップ文字列をコピーしました。安全な場所に貼り付けて保存してください。':'文字列を表示しました。全選択してコピーしてください。';};
$('restore-text').onclick=()=>stageImport($('backup-text').value,'backup-status');
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3000000)throw Error('ファイルが大きすぎます');stageImport(await file.text(),'import-status');}catch(error){$('import-status').textContent='読み込めません：'+error.message;}e.target.value='';};
$('cancel-restore').onclick=()=>{$('restore').close();pendingImport=null;pendingImportProfile=null;};$('confirm-restore').onclick=()=>{if(!pendingImport)return;state=pendingImport;pendingImport=null;pendingImportProfile=null;blocked=false;canSave=true;try{lastStored=localStorage.getItem(KEY);}catch{lastStored=null;}$('restore').close();const ok=persist();$(pendingImportStatus).textContent=ok?profile().name+'の記録を復元しました。':'一時的に復元しました。保存はできていません。';if(ok)$('storage-warning').hidden=true;parent();};
$('reset-album').onclick=()=>{const count=state.cards.filter(id=>D.cards.some(c=>c.id===id)).length;$('reset-album-summary').textContent='集めたカード '+count+'枚を0枚に戻します。この操作は元に戻せません。';$('reset-album-dialog').showModal();};
$('cancel-reset-album').onclick=()=>{$('reset-album-dialog').close();};
$('confirm-reset-album').onclick=()=>{$('reset-album-dialog').close();C.resetCards(state);const ok=persist();$('reset-status').textContent=ok?'図鑑のカードをリセットしました。書き順の記録と設定は残っています。':'一時的にリセットしました。保存はできていません。';parent();};
$('play').onclick=()=>begin();$('restart').onclick=()=>{if(blocked)return;if(C.discardActive(state)&&!persist())return;home();};for(const button of document.querySelectorAll('button[data-profile]'))button.onclick=()=>selectProfile(button.dataset.profile);$('again').onclick=()=>begin(courseOf(session()));$('rest').onclick=home;$('back').onclick=home;$('finish').onclick=home;$('collection').onclick=album;$('reward-collection').onclick=album;$('parents').onclick=parent;$('close-detail').onclick=()=>$('detail').close();document.querySelector('.brand').onclick=e=>{e.preventDefault();home();};
if(session()?.reward)showReward();else home();
