'use strict';
const C=RailCore,D=RAIL_DATA,KEY='hiragana-railway-v2',COUNTS=Object.fromEntries(Object.entries(D.characters).map(([c,v])=>[c,v.paths.length]));
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',screens=['home','game','reward','album','parent'];
let state=C.fresh(),lastStored=null,canSave=true,blocked=false,currentScreen='home',pointer=null,paths=[],samples=[],hintOn=false,animation=0,animationToken=0,demoing=false,pendingImport=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function warn(text){$('storage-warning').hidden=false;$('storage-warning').textContent=text;}
function conflict(){blocked=true;cancelDemo();pointer=null;if(!$('conflict').open)$('conflict').showModal();}
function persist(){if(blocked)return false;if(!canSave)return false;try{const current=localStorage.getItem(KEY);if(current!==lastStored){conflict();return false;}state.revision++;const data=JSON.stringify(state);localStorage.setItem(KEY,data);lastStored=data;return true;}catch{canSave=false;warn('このブラウザには保存できません。遊ぶことはできますが、閉じる前に「おうちの方へ」から記録を書き出してください。');return false;}}
try{lastStored=localStorage.getItem(KEY);if(lastStored)state=C.validate(JSON.parse(lastStored),COUNTS);}catch{canSave=false;blocked=true;warn('保存された記録を読み込めません。元のデータは残しています。');const b=document.createElement('button');b.textContent='保存せず一時的に遊ぶ';b.onclick=()=>{blocked=false;b.remove();warn('一時的なプレイです。元の記録は上書きしません。復元は「おうちの方へ」から行えます。');};$('storage-warning').append(b);}
window.addEventListener('storage',e=>{if((e.key===KEY||e.key===null)&&e.newValue!==lastStored)conflict();});$('reload').onclick=()=>location.reload();
const session=()=>C.active(state),q=()=>session()?.questions[session().index];
function svgEl(tag,attrs){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
function cancelDemo(){animationToken++;cancelAnimationFrame(animation);demoing=false;$('demo-dot').hidden=true;$('demo').disabled=false;}
function clearTrail(){pointer=null;$('trail').setAttribute('d','');}
function pause(reason){if(currentScreen==='game'&&pointer&&q()){C.uncertain(q(),reason);persist();}clearTrail();cancelDemo();}
function screen(id){pause('画面移動');currentScreen=id;for(const x of screens)$(x).hidden=x!==id;document.body.classList.toggle('child-screen',id!=='parent');document.body.classList.toggle('playing',id==='game');document.documentElement.classList.toggle('playing',id==='game');$('back').hidden=id==='home'||id==='game';if(id!=='game')window.scrollTo(0,0);}
function home(){screen('home');$('play').textContent=session()&&!session().reward?'つづきから →':'あそぶ →';$('owned').textContent=state.cards.filter(id=>D.cards.some(c=>c.id===id)).length+' / '+D.cards.length;}
function begin(){if(blocked)return;if(!session()||session().reward){C.start(state);persist();}if(blocked)return;screen('game');loadQuestion();}
function loadQuestion(){cancelDemo();clearTrail();const s=session(),item=q();if(!item){showReward();return;}hintOn=!!s.guide||item.assisted;if(!item.startedAt)item.startedAt=new Date().toISOString();if(s.guide&&!item.complete)C.assist(item,'補助モード');persist();$('strokes').replaceChildren();paths=D.characters[item.char].paths.map(d=>{const p=svgEl('path',{d,class:'stroke ghost'});$('strokes').append(p);return p;});samples=paths.map(p=>{const len=p.getTotalLength(),n=Math.ceil(len);return Array.from({length:n+1},(_,i)=>{const pt=p.getPointAtLength(i*len/n);return{x:pt.x,y:pt.y};});});$('board').setAttribute('aria-label',item.char+'を指で書くところ');$('char-label').textContent='「'+item.char+'」';$('round-label').textContent=(s.index+1)+' / 5';$('stations').innerHTML=s.questions.map((_,i)=>'<span class="'+(i<s.index?'done':i===s.index?'current':'')+'"></span>').join('');render();message(item.complete?'できた！ つぎへ すすもう':'じぶんで かいてみよう');}
function message(t){$('message').textContent=t;}
function render(){const item=q();if(!item)return;paths.forEach((p,i)=>p.setAttribute('class','stroke '+(i<item.stroke?'finished':'ghost')));$('hint-mark').replaceChildren();$('stroke-label').textContent=item.complete?'できた！':(item.stroke+1)+'かくめ';$('next').hidden=!item.complete;$('hint').disabled=item.complete;$('demo').disabled=item.complete||demoing;$('next').textContent=session().index===4?'カードを もらう →':'つぎへ →';if(hintOn&&!item.complete){const p=samples[item.stroke][0];$('hint-mark').append(svgEl('circle',{cx:p.x,cy:p.y,r:4.5,fill:'#fffefa',stroke:'#b78736','stroke-width':1}));const text=svgEl('text',{x:p.x,y:p.y+1.5,'text-anchor':'middle','font-size':4.5,fill:'#7b5416'});text.textContent=item.stroke+1;$('hint-mark').append(text);}}
function help(reason='ヒント',text='まるから しゅっぱつ！'){const item=q();if(!item||item.complete)return;C.assist(item,reason);hintOn=true;persist();render();message(text);}
function pos(e){return new DOMPoint(e.clientX,e.clientY).matrixTransform($('board').getScreenCTM().inverse());}
function drawTrail(c){const p=paths[q().stroke],len=p.getTotalLength();$('trail').setAttribute('d',p.getAttribute('d'));$('trail').style.strokeDasharray=len;$('trail').style.strokeDashoffset=len*(1-c.progress/(c.points.length-1));}
$('board').addEventListener('pointerdown',e=>{if(blocked||currentScreen!=='game'||q().complete||demoing||pointer||e.button>0)return;e.preventDefault();const p=pos(e);pointer={id:e.pointerId,last:p,travel:0,candidates:C.candidates(samples,p),chosen:null};$('board').setPointerCapture(e.pointerId);});
function move(e){if(!pointer||pointer.id!==e.pointerId)return;e.preventDefault();const p=pos(e),pnt=pointer;const distance=C.dist(pnt.last,p);pnt.travel+=distance;for(const cand of pnt.candidates)C.advance(cand,pnt.last,p);pnt.last=p;const chosen=pnt.chosen?.alive?pnt.chosen:C.resolve(pnt.candidates,pnt.travel);if(chosen){pnt.chosen=chosen;const item=q();if(chosen.index!==item.stroke||chosen.reverse){const kind=chosen.index!==item.stroke?'order':'direction';C.firstRecord(item,kind,chosen.index,chosen.reverse?'reverse':'forward');const txt=kind==='direction'?'まるから、こっちへ かこう':item.char==='や'&&item.stroke===1?'つぎは みぎうえの みじかい せん':item.char==='せ'&&item.stroke===1?'つぎは みぎの たてせん':'つぎは この せんだよ';clearTrail();help('自動案内',txt);return;}drawTrail(chosen);message(chosen.progress>=chosen.points.length-3?'ゆびを はなそう':'そのまま かこう');}
 if(pnt.travel>4&&!pnt.candidates.some(c=>c.alive)){C.uncertain(q(),'軌跡を判別できない');clearTrail();help('位置の補助','せんの ちかくから、もういちど');}}
$('board').addEventListener('pointermove',move);
function endPointer(e,cancel=false){if(!pointer||pointer.id!==e.pointerId)return;const p=pointer,item=q();const c=p.chosen||C.resolve(p.candidates,p.travel);const success=!cancel&&c?.alive&&c.index===item.stroke&&!c.reverse&&p.travel>=4&&c.progress>=c.points.length-3;clearTrail();if(success){C.firstRecord(item,'correct',item.stroke,'forward');item.stroke++;item.complete=item.stroke===paths.length;hintOn=!!session().guide;if(item.complete)message('できた！');else message('つぎは どこから？');persist();render();}else{C.uncertain(item,cancel?'タッチ中断':p.travel<4?'タップ・短い入力':'画の途中で指離し');persist();help('位置の補助',cancel?'もういちど この せんから':'この せんを、もういちど');}}
$('board').addEventListener('pointerup',e=>{if(pointer)move(e);endPointer(e);});$('board').addEventListener('pointercancel',e=>endPointer(e,true));$('board').addEventListener('lostpointercapture',e=>endPointer(e,true));
$('board').addEventListener('touchmove',e=>{if(currentScreen==='game'&&e.cancelable)e.preventDefault();},{passive:false});
window.addEventListener('resize',()=>{if(currentScreen==='game'){pause('画面サイズ変更');render();message('つづきから かこう');}});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('バックグラウンド移行');});window.addEventListener('pagehide',()=>pause('ページ離脱'));
for(const type of ['dblclick','gesturestart'])document.addEventListener(type,e=>{if(document.body.classList.contains('child-screen')&&e.cancelable)e.preventDefault();},{passive:false});
$('hint').onclick=()=>{pause('ヒント選択');help();};
$('demo').onclick=()=>{if(blocked||q()?.complete)return;pause('お手本選択');help('お手本');demoing=true;$('demo').disabled=true;const token=animationToken,item=q(),path=paths[item.stroke],len=path.getTotalLength(),duration=Math.max(800,len*13),start=performance.now();message('この せんを みていてね');function step(now){if(token!==animationToken)return;const f=Math.min(1,(now-start)/duration);$('trail').setAttribute('d',path.getAttribute('d'));$('trail').style.strokeDasharray=len;$('trail').style.strokeDashoffset=len*(1-f);const p=path.getPointAtLength(len*f);$('demo-dot').hidden=false;$('demo-dot').setAttribute('cx',p.x);$('demo-dot').setAttribute('cy',p.y);if(f<1)animation=requestAnimationFrame(step);else{cancelDemo();clearTrail();render();message('まるから かいてみよう');}}animation=requestAnimationFrame(step);};
$('next').onclick=()=>{if(blocked||!q()?.complete)return;const s=session();s.index++;if(s.index===5){C.award(state,D.cards.map(c=>c.id));persist();showReward();}else{persist();loadQuestion();}};
function photo(img,card){img.src=card.image;img.alt=card.name;img.hidden=false;img.nextElementSibling?.classList.contains('photo-error')&&img.nextElementSibling.remove();img.onerror=()=>{img.hidden=true;const box=document.createElement('div');box.className='photo-error';box.textContent='しゃしんを よみこめませんでした。';const b=document.createElement('button');b.textContent='もういちど';b.onclick=()=>photo(img,card);box.append(b);img.after(box);};}
function showReward(){const s=session(),card=D.cards.find(c=>c.id===s?.reward);if(!card){home();return;}screen('reward');photo($('reward-photo'),card);$('reward-title').textContent=s.repeat?'きょうの 1まい！':'カードを ゲット！';$('reward-kicker').textContent=s.repeat?'TODAY’S TRAIN':'NEW TRAIN CARD';$('reward-name').textContent=card.reading;$('reward-category').textContent=card.category;$('reward-number').textContent=card.name;$('reward-text').textContent=state.cards.filter(id=>D.cards.some(c=>c.id===id)).length===D.cards.length?'ぜんぶ あつまった！ また あそぼう。':'5もじ、さいごまで できたね。';}
function album(){screen('album');const owned=state.cards.filter(id=>D.cards.some(c=>c.id===id));$('album-count').textContent=owned.length+' / '+D.cards.length;$('cards').replaceChildren();for(const card of D.cards){if(!owned.includes(card.id)){const empty=document.createElement('div');empty.className='empty-card';empty.innerHTML='<b>？</b><span>これから あえる でんしゃ</span>';$('cards').append(empty);continue;}const button=document.createElement('button');button.className='train-card';const img=document.createElement('img');photo(img,card);const text=document.createElement('div');text.innerHTML='<small>'+esc(card.category)+'</small>'+esc(card.reading);button.append(img,text);button.onclick=()=>detail(card);$('cards').append(button);}}
function detail(card){photo($('detail-photo'),card);$('detail-category').textContent=card.category;$('detail-name').textContent=card.reading;$('detail-fact').textContent=card.fact;$('detail-credit').innerHTML='<p>'+esc(card.name)+'</p><p>原題：'+esc(card.sourceTitle)+'</p><p>'+esc(card.credit)+' / <a target="_blank" rel="noopener" href="'+esc(card.source)+'">写真原典</a> / <a target="_blank" rel="noopener" href="'+esc(card.licenseUrl)+'">'+esc(card.license)+'</a></p><p>'+esc(card.change)+'</p><a target="_blank" rel="noopener" href="'+esc(card.factSource)+'">豆知識の根拠</a>（'+esc(card.checked)+'確認）';$('detail').showModal();}
const kinds={order:'順番',direction:'方向',uncertain:'判定保留',unobserved:'補助から開始',correct:'正しい画を選択'};
function parent(){screen('parent');const rows=state.sessions.flatMap(s=>s.questions.filter(q=>q.startedAt).map(q=>({q,date:q.startedAt})));$('record-range').textContent=rows.length?'記録 '+rows.length+'問 ／ '+new Date(state.sessions[0].createdAt).toLocaleDateString('ja-JP')+'〜（直近100回分まで）':'まだ記録はありません。';const unknownCards=state.cards.filter(id=>!D.cards.some(c=>c.id===id)).length,unknownQuestions=rows.filter(r=>!C.CHARS.includes(r.q.char)).length;if(unknownCards||unknownQuestions)$('record-range').textContent+=' ／ この版では未対応のカード '+unknownCards+'件・文字記録 '+unknownQuestions+'件は保持しています。';$('records').replaceChildren();for(const char of C.CHARS){const entries=rows.filter(r=>r.q.char===char),total=entries.length;const independent=entries.filter(({q})=>q.complete&&!q.assisted&&!q.uncertain&&Object.values(q.records).every(r=>r.kind==='correct'&&!r.assisted)).length;const helped=entries.filter(({q})=>q.complete&&q.assisted).length;const mistakes=entries.filter(({q})=>Object.values(q.records).some(r=>r.kind==='order'&&!r.assisted)).length;const directions=entries.filter(({q})=>Object.values(q.records).some(r=>r.kind==='direction'&&!r.assisted)).length;const uncertain=entries.filter(({q})=>q.uncertain).length;const record=document.createElement('details');record.className='record';const sum=document.createElement('summary');sum.innerHTML='<span class="letter">'+char+'</span><span class="count">'+(total?'出題 '+total+'回 · 案内なし完了 '+independent+'回<br>順番の取り違え '+mistakes+'回 · 方向の取り違え '+directions+'回 · 補助付き完了 '+helped+'回 · 保留/中断 '+uncertain+'回':'未出題')+'</span>';record.append(sum);const list=document.createElement('ul');for(const {q,date}of entries.slice(-10).reverse()){const li=document.createElement('li');let t=new Date(date).toLocaleString('ja-JP')+'：'+(q.complete?'完了':'未完了')+(q.assisted?'（補助あり）':'');for(const r of Object.values(q.records)){t+=' ／ '+(r.expected+1)+'画目：'+kinds[r.kind]+(r.observed!==null?' → '+(r.observed+1)+'画目を選択':'')+(r.direction==='reverse'?'・逆方向':'')+(r.assisted?'［補助後］':'')+(r.help?'［'+r.help+'］':'')+(r.interrupted?'［'+r.interrupted+'］':'');}li.textContent=t;list.append(li);}record.append(list);const b=document.createElement('button');b.textContent=state.settings.focus.includes(char)?'重点に設定済み':'次にも確かめる';b.onclick=()=>{if(!state.settings.focus.includes(char))state.settings.focus.push(char);persist();parent();};record.append(b);$('records').append(record);}
 for(const [id,key]of [['focus-options','focus'],['pool-options','pool']]){$(id).replaceChildren();for(const c of C.CHARS){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=state.settings[key].includes(c);input.onchange=()=>{state.settings[key]=input.checked?[...state.settings[key],c]:state.settings[key].filter(x=>x!==c);persist();$('settings-result').textContent='次の5問から反映します。';};label.append(input,document.createTextNode(' '+c));$(id).append(label);}}$('guide').checked=state.settings.guide;}
$('guide').onchange=()=>{state.settings.guide=$('guide').checked;persist();};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hiragana-railway-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3000000)throw Error('ファイルが大きすぎます');pendingImport=C.validate(JSON.parse(await file.text()),COUNTS);$('restore-summary').textContent='カード '+pendingImport.cards.length+'種類・'+pendingImport.sessions.length+'回分の記録です。';$('restore').showModal();}catch(error){$('import-status').textContent='読み込めません：'+error.message;}e.target.value='';};
$('cancel-restore').onclick=()=>{$('restore').close();pendingImport=null;};$('confirm-restore').onclick=()=>{if(!pendingImport)return;state=pendingImport;pendingImport=null;blocked=false;canSave=true;try{lastStored=localStorage.getItem(KEY);}catch{lastStored=null;}$('restore').close();const ok=persist();$('import-status').textContent=ok?'記録を復元しました。':'一時的に復元しました。保存はできていません。';if(ok)$('storage-warning').hidden=true;parent();};
$('play').onclick=begin;$('again').onclick=begin;$('rest').onclick=home;$('back').onclick=home;$('finish').onclick=home;$('collection').onclick=album;$('reward-collection').onclick=album;$('parents').onclick=parent;$('close-detail').onclick=()=>$('detail').close();document.querySelector('.brand').onclick=e=>{e.preventDefault();home();};
if(session()?.reward)showReward();else home();
