const assert=require('node:assert/strict');
const C=require('../core.js');
const D=require('../data/index.js');
const ADDED=['い','つ','し','く','へ','り','こ','う','て','と','に','か','た','な','の'];
const PATCHED=['き','け','さ','ち','は','ひ','ま','み','ゆ','わ'];
const counts=Object.fromEntries(Object.entries(D.characters).map(([char,data])=>[char,data.paths.length]));
assert.deepEqual(C.GROUPS.hiragana,['や','せ','ふ','ほ','も','む','よ',...ADDED,'あ','え','お',...PATCHED,'ら','る','れ','す','そ','ぬ','ね','め','ろ','を','ん']);
assert.equal(C.GROUPS.hiragana.length,46);
assert.deepEqual([...'あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん'].filter(c=>!C.GROUPS.hiragana.includes(c)),[],'every basic hiragana is included');
let s=C.fresh();assert.deepEqual(C.start(s).questions.map(q=>q.char),['や','ふ','せ','ほ','も']);
assert.deepEqual(C.start(s).questions.map(q=>q.char),['や','む','せ','よ','い']);
s.settings.pool=['や'];assert.deepEqual(C.start(s,'hiragana').questions.map(q=>q.char),Array(5).fill('や'));
const addedState=C.fresh();addedState.settings.focus=[];addedState.settings.pool=ADDED;const addedSeen=new Set();for(let round=0;round<3;round++)for(const q of C.start(addedState,'hiragana').questions)addedSeen.add(q.char);assert.deepEqual([...addedSeen],ADDED);assert.ok(addedState.sessions.flatMap(session=>session.questions).every(q=>ADDED.includes(q.char)));console.log('PASS: all 15 added hiragana rotate through three five-question sets');
const allHiraganaState=C.fresh();allHiraganaState.settings.focus=[];const allHiraganaSeen=new Set();for(let round=0;round<10;round++)for(const q of C.start(allHiraganaState,'hiragana').questions)allHiraganaSeen.add(q.char);assert.deepEqual([...allHiraganaSeen].sort(),[...C.GROUPS.hiragana].sort());console.log('PASS: all 46 hiragana rotate when the pool is unrestricted');
const kanjiState=C.fresh(),seen=new Set();for(let round=0;round<5;round++)for(const q of C.start(kanjiState,'kanji').questions)seen.add(q.char);assert.deepEqual([...seen].sort(),[...C.GROUPS.kanji].sort());assert.ok(kanjiState.sessions.every(session=>session.course==='kanji'));assert.ok(kanjiState.sessions.flatMap(session=>session.questions).every(q=>C.GROUPS.kanji.includes(q.char)));console.log('PASS: separate hiragana/kanji courses and all 22 kanji rotate into five rounds');
const independent=C.fresh();C.start(independent,'hiragana');assert.deepEqual(C.start(independent,'kanji').questions.map(q=>q.char),['一','二','三','四','五']);const legacy=JSON.parse(JSON.stringify(independent));delete legacy.kanjiCursor;delete legacy.kanjiFocusCursor;assert.doesNotThrow(()=>C.validate(legacy,counts));assert.equal(legacy.kanjiCursor,0);console.log('PASS: kanji starts at one after hiragana use and legacy saves gain independent cursors');
assert.deepEqual(C.GROUPS.katakana,[...'シツソンアイウエオカキクケコサスセタチテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲ']);assert.equal(C.GROUPS.katakana.length,46);const katakanaState=C.fresh();katakanaState.settings.focus=[];C.start(katakanaState,'hiragana');C.start(katakanaState,'kanji');const katakanaCursorBefore={cursor:katakanaState.cursor,kanjiCursor:katakanaState.kanjiCursor};const firstKatakana=C.start(katakanaState,'katakana');assert.equal(firstKatakana.course,'katakana');assert.deepEqual(firstKatakana.questions.map(q=>q.char),['シ','ツ','ソ','ン','ア'],'katakana starts with シ・ツ・ソ・ン');const secondKatakana=C.start(katakanaState,'katakana');assert.deepEqual(secondKatakana.questions.map(q=>q.char),['イ','ウ','エ','オ','カ'],'katakana rotation continues in gojuon order');assert.deepEqual({cursor:katakanaState.cursor,kanjiCursor:katakanaState.kanjiCursor},katakanaCursorBefore,'katakana leaves hiragana and kanji cursors untouched');assert.equal(katakanaState.katakanaCursor,10);const allKatakanaSeen=new Set([...firstKatakana.questions,...secondKatakana.questions].map(q=>q.char));for(let round=0;round<8;round++)for(const q of C.start(katakanaState,'katakana').questions)allKatakanaSeen.add(q.char);assert.equal(allKatakanaSeen.size,46,'all 46 katakana rotate within ten sets');
const katakanaFocus=C.fresh();katakanaFocus.settings.focus=['や','ン'];assert.deepEqual(C.start(katakanaFocus,'katakana').questions.map(q=>q.char).filter(c=>c==='ン').length>=1,true);assert.ok(C.start(katakanaFocus,'katakana').questions.every(q=>C.GROUPS.katakana.includes(q.char)),'hiragana focus stays out of katakana');assert.equal(katakanaFocus.focusCursor,0,'katakana focus uses its own cursor');
const katakanaLegacy=JSON.parse(JSON.stringify(independent));delete katakanaLegacy.katakanaCursor;delete katakanaLegacy.katakanaFocusCursor;assert.doesNotThrow(()=>C.validate(katakanaLegacy,counts));assert.equal(katakanaLegacy.katakanaCursor,0);assert.equal(katakanaLegacy.katakanaFocusCursor,0);const katakanaSaved=C.validate(JSON.parse(JSON.stringify(katakanaState)),counts);assert.equal(katakanaSaved.sessions.at(-1).course,'katakana');const badKatakanaCursor=JSON.parse(JSON.stringify(katakanaState));badKatakanaCursor.katakanaCursor=-1;assert.throws(()=>C.validate(badKatakanaCursor,counts));console.log('PASS: all 46 katakana rotate from シ・ツ・ソ・ン with their own cursors and older saves load');
const ids=D.cards.map(card=>card.id),shiny=C.fresh(),midIndex=Math.floor(ids.length*.5),midCard=ids[midIndex];
function finish(state,mark){const current=C.start(state);mark?.(current);for(const item of current.questions){item.stroke=counts[item.char];item.complete=true;}current.index=5;return current;}
const first=finish(shiny);assert.equal(C.award(shiny,ids,()=>0),'redwing');assert.deepEqual(shiny.shinyCards,[],'first collection lap does not awaken cards');assert.equal(first.shinyAwarded,false);
shiny.cards=ids.slice();const derailed=finish(shiny,current=>{current.questions[0].uncertain=true;C.firstRecord(current.questions[0],'uncertain');C.assist(current.questions[0],'位置の補助');});assert.equal(C.award(shiny,ids,()=>.5),midCard);assert.deepEqual(shiny.shinyCards,[midCard],'derailment and assistance do not disqualify');assert.equal(derailed.shinyAwarded,true);assert.equal(C.award(shiny,ids,()=>0),midCard,'award is idempotent');
const wrong=finish(shiny,current=>{C.firstRecord(current.questions[0],'order',1);C.assist(current.questions[0],'自動案内');});assert.equal(C.award(shiny,ids,()=>0),ids[0]);assert.equal(wrong.shinyAwarded,false);assert.deepEqual(shiny.shinyCards,[midCard]);
const reverse=finish(shiny,current=>C.firstRecord(current.questions[0],'direction',0,'reverse'));assert.equal(C.award(shiny,ids,()=>0),ids[0]);assert.equal(reverse.shinyAwarded,false);
const recovered=finish(shiny);assert.equal(C.award(shiny,ids,()=>0),ids[0]);assert.equal(recovered.shinyAwarded,true);assert.deepEqual(shiny.shinyCards,[midCard,ids[0]]);
shiny.shinyCards=ids.slice();const allShiny=finish(shiny);assert.equal(C.award(shiny,ids,()=>.5),midCard,'all shiny cards use the full uniform pool');assert.equal(allShiny.shinyAwarded,false);assert.doesNotThrow(()=>C.validate(JSON.parse(JSON.stringify(shiny)),counts));
const oldSave=JSON.parse(JSON.stringify(shiny));delete oldSave.shinyCards;for(const item of oldSave.sessions)delete item.shinyAwarded;assert.doesNotThrow(()=>C.validate(oldSave,counts));assert.deepEqual(oldSave.shinyCards,[],'legacy save gains empty shiny collection');
const badShiny=JSON.parse(JSON.stringify(shiny));badShiny.shinyCards=['missing'];assert.throws(()=>C.validate(badShiny,counts));const duplicateShiny=JSON.parse(JSON.stringify(shiny));duplicateShiny.shinyCards=[ids[0],ids[0]];assert.throws(()=>C.validate(duplicateShiny,counts));
const shinyBackup=JSON.stringify(shiny);const restored=C.validate(JSON.parse(shinyBackup),counts);assert.deepEqual(restored.shinyCards,ids);C.resetCards(restored);assert.deepEqual(restored.cards,[]);assert.deepEqual(restored.shinyCards,[]);assert.doesNotThrow(()=>C.validate(restored,counts));console.log('PASS: second lap shiny eligibility, derailment exemption, unshiny priority, random after completion, old saves, backup and card-only reset');
for(const kind of ['order','direction'])for(let position=0;position<5;position++){const state=C.fresh();state.cards=ids.slice();const current=finish(state,session=>{const item=session.questions[position];C.recordMistake(session,item,{index:kind==='order'?1:0,reverse:kind==='direction'});C.uncertain(item,'脱線後にやり直し');});assert.equal(current.orderMistake,true);assert.equal(C.award(state,ids,()=>0),ids[0]);assert.deepEqual(state.shinyCards,[],`${kind} on question ${position+1} prevents shiny`);assert.equal(current.shinyAwarded,false);assert.doesNotThrow(()=>C.validate(JSON.parse(JSON.stringify(state)),counts));}
const correctLine=Array.from({length:21},(_,i)=>({x:10,y:10+i})),wrongLine=correctLine.map(p=>({x:p.x+40,y:p.y}));let wrongStarts=C.candidates([correctLine,wrongLine],wrongLine[0]);for(const candidate of wrongStarts)C.advance(candidate,wrongLine[0],{x:wrongLine[0].x+8,y:wrongLine[0].y});assert.equal(C.resolve(wrongStarts,8),null,'short wrong start previously looked uncertain');assert.equal(C.wrongChoice(wrongStarts,0,8).index,1,'a wrong-only start is still a mistake');let reverseStart=C.candidates([correctLine],correctLine.at(-1));for(const candidate of reverseStart)C.advance(candidate,correctLine.at(-1),{x:correctLine.at(-1).x+8,y:correctLine.at(-1).y});assert.equal(C.wrongChoice(reverseStart,0,8).reverse,true,'short reverse start is still a mistake');let derailStart=C.candidates([correctLine,wrongLine],correctLine[0]);for(const candidate of derailStart)C.advance(candidate,correctLine[0],{x:correctLine[0].x+8,y:correctLine[0].y});assert.equal(C.wrongChoice(derailStart,0,8),null,'derailing from the correct stroke remains safe');assert.equal(C.wrongChoice(wrongStarts,0,2),null,'a tap is not a mistake');console.log('PASS: order and reverse mistakes on any of five questions block shiny; wrong-only starts count, correct-stroke derailment stays safe');
const resumedState=C.fresh();resumedState.cards=ids.slice();const interruptedSet=C.start(resumedState);C.recordMistake(interruptedSet,interruptedSet.questions[0],{index:1,reverse:false});const resumed=C.validate(JSON.parse(JSON.stringify(resumedState)),counts);assert.equal(C.active(resumed).orderMistake,true);for(const item of C.active(resumed).questions){item.stroke=counts[item.char];item.complete=true;}C.active(resumed).index=5;C.award(resumed,ids,()=>0);assert.deepEqual(resumed.shinyCards,[],'mistake remains disqualifying after save and resume');
s=C.fresh();for(let i=0;i<105;i++){const active=C.start(s);for(const q of active.questions){q.complete=true;q.stroke=counts[q.char];}active.index=5;C.award(s,['redwing','500','n700'],()=>.2);const card=active.reward;C.award(s,['redwing','500','n700'],()=>.9);assert.equal(active.reward,card);}assert.equal(s.sessions.length,100);assert.equal(s.cards.length,3);assert.equal(C.active(s).repeat,true);assert.doesNotThrow(()=>C.validate(JSON.parse(JSON.stringify(s)),counts));
const reset=JSON.parse(JSON.stringify(s)),keptSessions=JSON.stringify(reset.sessions),keptSettings=JSON.stringify(reset.settings);C.resetCards(reset);assert.deepEqual(reset.cards,[]);assert.equal(JSON.stringify(reset.sessions),keptSessions);assert.equal(JSON.stringify(reset.settings),keptSettings);assert.equal(reset.activeId,null);assert.doesNotThrow(()=>C.validate(reset,counts));const inProgress=C.fresh(),running=C.start(inProgress);C.resetCards(inProgress);assert.equal(inProgress.activeId,running.id);console.log('PASS: card-only reset preserves records, settings and unfinished session');
const abandoned=C.fresh(),completed=C.start(abandoned);for(const item of completed.questions){item.stroke=counts[item.char];item.complete=true;}completed.index=5;C.award(abandoned,['redwing'],()=>0);const unfinished=C.start(abandoned,'kanji');assert.equal(C.discardActive(abandoned),true);assert.equal(abandoned.activeId,null);assert.equal(abandoned.sessions.some(item=>item.id===unfinished.id),false);assert.equal(abandoned.sessions.some(item=>item.id===completed.id),true);assert.equal(C.discardActive(abandoned),false);assert.doesNotThrow(()=>C.validate(abandoned,counts));console.log('PASS: start-over discards only the unfinished active session');
const malformed=JSON.parse(JSON.stringify(s));malformed.sessions[0].questions[0].stroke=88;assert.throws(()=>C.validate(malformed,counts));assert.throws(()=>C.validate({...s,version:1},counts));
const q={stroke:1,assisted:false,records:{}};C.firstRecord(q,'order',2);C.assist(q,'自動案内');C.firstRecord(q,'correct',1);assert.equal(q.records['1'].kind,'order');assert.equal(q.records['1'].assisted,false);q.stroke=2;C.firstRecord(q,'correct',2);assert.equal(q.records['2'].assisted,true);
const line=Array.from({length:51},(_,i)=>({x:10,y:10+i}));let list=C.candidates([line],line[0]);C.advance(list[0],line[0],line.at(-1));assert.equal(list[0].alive,true);assert.ok(list[0].progress>=line.length-C.END_MARGIN);assert.equal(list[0].reachedEnd,true);C.advance(list[0],line.at(-1),{x:35,y:35});assert.equal(list[0].alive,true,'post-endpoint flick ignored');assert.equal(list[0].reachedEnd,true);assert.equal(C.resolve(list,50).reverse,false);
const crossed=C.candidates([line],line[0])[0];C.advance(crossed,line[0],{x:10,y:80});assert.equal(crossed.alive,true,'endpoint crossing locks within one sparse move');assert.equal(crossed.reachedEnd,true);
const offsetLine=line.map(p=>({x:p.x+9,y:p.y}));list=C.candidates([line],offsetLine[0]);assert.equal(list.length,1,'slightly offset start accepted');C.advance(list[0],offsetLine[0],offsetLine.at(-1));assert.equal(list[0].alive,true,'slightly offset path accepted');assert.equal(C.resolve(list,50).reverse,false);
assert.equal(C.candidates([line],{x:line[0].x+11,y:line[0].y}).length,0,'distant start rejected');
list=C.candidates([line],line[0]);C.advance(list[0],line[0],line[35]);C.advance(list[0],line[35],{x:30,y:45});assert.equal(list[0].alive,false,'pre-endpoint deviation rejected');assert.equal(list[0].reachedEnd,false);
list=C.candidates([line],line.at(-1));for(const c of list)C.advance(c,line.at(-1),line[0]);assert.equal(C.resolve(list,50).reverse,true);
const curve=Array.from({length:101},(_,i)=>({x:30+25*Math.cos(Math.PI*i/100),y:30+25*Math.sin(Math.PI*i/100)}));list=C.candidates([curve],curve[0]);for(const c of list)C.advance(c,curve[0],curve.at(-1));assert.equal(list.some(c=>c.alive),false,'curved shortcut rejected');
console.log('PASS: rotation, single-letter pool, 100-session cap, idempotent reward, all-collected behavior, validation, assistance classification, tolerant tracing, forward/reverse/shortcut');

const interrupted={stroke:0,assisted:false,records:{}};C.uncertain(interrupted,'cancel');C.assist(interrupted);C.firstRecord(interrupted,'correct',0);assert.equal(interrupted.records['0'].kind,'correct');assert.equal(interrupted.records['0'].assisted,true);assert.equal(interrupted.uncertain,true);console.log('PASS: uncertainty retained while first classifiable choice is recorded after help');
// A stroke that folds back just below itself (like そ) must survive a wobbling finger, while reversing or stopping short still fails.
{const fold=[...Array.from({length:31},(_,i)=>({x:30+i,y:40})),...Array.from({length:20},(_,i)=>({x:59-i,y:41.5})),...Array.from({length:30},(_,i)=>({x:40,y:42+i}))];
const trace=input=>{const list=C.candidates([fold],input[0]);let travel=0;for(let i=1;i<input.length;i++){travel+=C.dist(input[i-1],input[i]);for(const c of list)C.advance(c,input[i-1],input[i]);}return C.resolve(list,travel);};
const wobble=fold.map((p,i)=>({x:p.x+Math.sin(i*.25)*2,y:p.y+Math.cos(i*.2)*2}));const done=trace(wobble);assert.ok(done&&done.reachedEnd&&!done.reverse,'wobbling trace passes the fold');
const back=trace(fold.slice().reverse());assert.ok(back&&back.reverse,'reverse trace is still classified as reverse');
const short=trace(fold.slice(0,45));assert.ok(!short?.reachedEnd,'stopping inside the fold does not complete');
const strict=C.candidates([fold],wobble[0]).find(c=>!c.reverse);for(let i=1;i<wobble.length&&strict.alive;i++)C.advance(strict,wobble[i-1],wobble[i],10,true);assert.equal(strict.alive,false,'strict backtrack cut-off is unchanged');
console.log('PASS: tracing follows a fold-back stroke with wobble, keeps reverse and early-stop failures, strict mode unchanged');}
